user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid; 

events {
    worker_connections 768;
}

http {

  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  log_format main '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';

  access_log /var/log/nginx/access.log main;

  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  types_hash_max_size 2048;
  client_max_body_size 20M;


  # keep proxy directives in one place
  proxy_set_header        Host              $host;
  proxy_set_header        X-Real-IP         $remote_addr;
  proxy_set_header        X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header        X-Forwarded-Proto $scheme;
  proxy_set_header        X-SSL-Request     1;
  proxy_buffering         off;
  proxy_connect_timeout   90;
  proxy_send_timeout      90;
  proxy_read_timeout      540;


  ##
  # SSL Settings
  ##
  ssl_prefer_server_ciphers on;
  ssl_ciphers ECDHE+AESGCM:ECDHE+AES256:ECDHE+AES128:!aNULL:!ADH:!AECDH:!NULL:!MD5:!3DES:!RC4:!EXP;
  ssl_protocols TLSv1.2 TLSv1.3;

  # Include server configurations
  include /etc/nginx/conf.d/*.conf;

}

